PIECE_KEY_BASE: int = 3
PIECE_KEY_NUMBER_DIGITS: int = 4
PIECE_HIGHEST_DIGIT: str = str(PIECE_KEY_BASE - 1)
MAX_PIECE_KEY: str = ''.join([PIECE_HIGHEST_DIGIT]*PIECE_KEY_NUMBER_DIGITS)
MAX_NUMBER_PIECE_KEYS: int = int(MAX_PIECE_KEY, base=PIECE_KEY_BASE) + 1
PIECE_KEY_DIGITS: str =  ''.join([str(digit) for digit in range(PIECE_KEY_BASE)])
ASTERISK: str = '*'
ASTERISK_PIECE_KEY :str = ASTERISK * PIECE_KEY_NUMBER_DIGITS
PIECE_KEY_INDEX_LENGTH: int = len(str(MAX_NUMBER_PIECE_KEYS))

if __name__ == '__main__':
    assert len(PIECE_KEY_DIGITS) == PIECE_KEY_BASE
    assert MAX_PIECE_KEY == '2222'
    assert MAX_NUMBER_PIECE_KEYS == PIECE_KEY_BASE ** PIECE_KEY_NUMBER_DIGITS


